# ASCII TABLE: http://www.physics.udel.edu/~watson/scen103/ascii.html
CTRL_Q_DECIMAL = 17
CTRL_U_DECIMAL = 21
CTRL_W_DECIMAL = 23
CTRL_P_DECIMAL = 16
CTRL_N_DECIMAL = 14
CTRL_B_DECIMAL = 2
CTRL_F_DECIMAL = 6
RETURN_DECIMAL = 13
BACKSPACE_DECIMAL = 127
