from . import ascii as C

EXIT_CHAR = chr(C.CTRL_Q_DECIMAL)
UNDO_CHAR = chr(C.CTRL_U_DECIMAL)
SAVE_CHAR = chr(C.CTRL_W_DECIMAL)
CURSOR_UP_CHAR = chr(C.CTRL_P_DECIMAL)
CURSOR_DOWN_CHAR = chr(C.CTRL_N_DECIMAL)
CURSOR_LEFT_CHAR = chr(C.CTRL_B_DECIMAL)
CURSOR_RIGHT_CHAR = chr(C.CTRL_F_DECIMAL)
SPLIT_LINE_CHAR = chr(C.RETURN_DECIMAL)
DELETE_BEFORE_CURSOR_CHAR = chr(C.BACKSPACE_DECIMAL)
