CURSOR_MOVE_UP = "MOVE_UP"
CURSOR_MOVE_DOWN = "MOVE_DOWN"
CURSOR_MOVE_LEFT = "MOVE_LEFT"
CURSOR_MOVE_RIGHT = "MOVE_RIGHT"
CURSOR_RESET_COLUMN = "RESET_COLUMN"

CURSOR_MOVEMENTS = (
    CURSOR_MOVE_UP,
    CURSOR_MOVE_DOWN,
    CURSOR_MOVE_LEFT,
    CURSOR_MOVE_RIGHT,
    CURSOR_RESET_COLUMN,
)
